### ISSUE TITLE
On the weapons page, western revolver doesn't have the highest damage receiver as an option

### ISSUE THREAD

**Issue by shueseman** [akarnokd/rng-76#1]
For whatever reason, the severe and refined receivers do the most damage for the western revolver.   For most weapons, it's the hardened.   Could you include severe or refined receiver as an option when thats the chosen weapon?

Thanks for your work on this page. :)

**Comment by akarnokd** [comment]
I think it's a bug in the game. 

From the datafiles, the [Hardened receiver](https://nukacrypt.com/database/json/0052708C) has only a keyword add property and the mod adds 25% more damage.

For the [Severe receiver](https://nukacrypt.com/database/json/0052708D), it should be 12.5% but it lists a bonus damage section of 25% so 1.125 * 1.25 => 40.6% more damage. The same goes for the Refined receiver.

I've added the receivers and their bugged versions for now.

**Comment by shueseman** [comment]
Thanks for that.  I agree that FO76 is bugged in regards to this weapon.   I tested out your changes and the numbers reported in your simulator don't match the numbers I see in-game.

For a level 50 Western revolver, with Refined (bugged) receiver, Junkie's prefix, 5 addictions, Bloody Mess Rank 3, Weapon-specific boost of 55%, your simulator reports 244.40 damage.  In-game I am seeing 238.   You do have the correct number if i use the Hardened Receiver (217).     Maybe a rounding error with the new receivers?

**Comment by akarnokd** [comment]
Looks like the bugged effect is additive, so 12.5% + 25% = 37.5%. Updated the calculator. I get 238.9 so there could be still some rounding hidden somewhere. (Note that the weapon card rounds up while the weapon-inventory rounds down in the game.)

https://akarnokd.github.io/rng-76/weapons.html?left=R_W-WesternRevolver_L-50_ModReceiver-Refined(Bugged)_Prefix-Junkies_PHP-100_EHP-99_Hits-0_Addicts-5_BloodyMess-15_Kills-6_Boost-55_Other-0

**Comment by shueseman** [comment]
looks close enough for me, thanks :)
