### ISSUE TITLE
XP Calculator: Meat XP boosts broken

### ISSUE THREAD

**Issue by jakdevaney** [akarnokd/rng-76#18]
Selecting "Canned Meat Stew" in the XP Calculator does not apply the bonus.

This is because the "CannedMeatSte**e**w" has an extra "e" here:
https://github.com/akarnokd/rng-76/blob/76de709927ba446a51225141fdc2a943396a934f/xp.html#L262

Also Tasty Squirrel Stew is missing from the list.

**Comment by akarnokd** [comment]
Thanks, I'll look into these tomorrow.

**Comment by akarnokd** [comment]
Fixed.
