### ISSUE TITLE
XP Calculator: Legendary Intelligence Lv4 not correct

### ISSUE THREAD

**Issue by jakdevaney** [akarnokd/rng-76#19]
Selecting level 4 of "Legendary Intelligence" only applies 4 points of Intelligence instead of the actual 5 you get in game.
https://github.com/akarnokd/rng-76/blob/327ff4d1af642462a1996eb3ea0e7125bb9f43f9/xp.html#L1139

Also the tooltip could be updated. The SPECIAL Legendary Perks do stack with your base SPECIAL in the _live_ game now.
https://github.com/akarnokd/rng-76/blob/327ff4d1af642462a1996eb3ea0e7125bb9f43f9/xp.html#L885

**Comment by akarnokd** [comment]
Sorry for the late answer, fixed it.
