### ISSUE TITLE
Black Powder Blunderbuss speed key is misspelled

### ISSUE THREAD

**Issue by jambolo** [akarnokd/rng-76#2]
In weapons.html at line 2461, the Black Powder Blunderbuss speed key is misspelled so the value is wrong:

`speeD: 0.2`

**Comment by akarnokd** [comment]
Thanks! Fixed.

https://akarnokd.github.io/rng-76/weapons.html?left=R_W-BlackPowderBlunderbuss_L-50_PHP-100_EHP-99_Hits-0_Addicts-0_Kills-6_Other-0
