### ISSUE TITLE
Adding "Vats Crits do +50% damage" to the Alien Desintegator double its damage

### ISSUE THREAD

**Issue by DEVolkan** [akarnokd/rng-76#23]
https://akarnokd.github.io/rng-76/weapons.html?left=R_W-AlienDesintegrator_L-50_ModReceiver-Standard_Major-VATSCrit50_CalcMode-P34&right=R_W-AlienDesintegrator_L-50_ModReceiver-Standard_CalcMode-P34

**Comment by akarnokd** [comment]
Fixed. Please let me know if something else broke.
