### ISSUE TITLE
Uncaught ReferenceError: dailyOpsMoleMiners is not defined on https://akarnokd.github.io/rng-76/daily.html

### ISSUE THREAD

**Issue by Luminarcy** [akarnokd/rng-76#27]
Uncaught ReferenceError: dailyOpsMoleMiners is not defined
    at daily.html:17051:42
    
https://akarnokd.github.io/rng-76/daily.html
![chrome_2023-03-06_17-09-11](https://user-images.githubusercontent.com/42573485/223133231-f49e306f-dcad-4be7-a73d-d60d261d5edd.png)

**Comment by akarnokd** [comment]
Oops. Fixed. Thanks for reporting.
