### ISSUE TITLE
The speed is wrong for Old Guard's 10mm SMG

### ISSUE THREAD

**Issue by jambolo** [akarnokd/rng-76#3]
In weapons.html at line 2339, the speed for Old Guard's 10mm SMG is 100, but I think it should be 10.0.

**Comment by akarnokd** [comment]
Thanks! Fixed.

https://akarnokd.github.io/rng-76/weapons.html?left=R_W-OldGuards10mmSMG_L-50_ModReceiver-Refined_ModMagazine-Piercing_ModMuzzle-Standard_Prefix-Antiarmor_PHP-100_EHP-99_Hits-0_Addicts-0_Kills-6_Other-0
