### ISSUE TITLE
Patch 50 anti-armor + perforating calculation

### ISSUE THREAD

**Issue by levimeahan** [akarnokd/rng-76#36]
I noticed the notes for Patch 44 say the anti-armor legendary mod is now additive, meaning an Anti-Armor+perforating gun is 90% armor pen. But when I set calculation mode to patch 50, it says 70% (old value)

![image](https://github.com/akarnokd/rng-76/assets/1691258/77d4f19a-cc90-4b02-978c-74a268d11604)

Did the anti-armor change get reverted after Patch 44, or is this a bug in the calculator?

**Comment by akarnokd** [comment]
Hey, thanks for the report. 

I'm not aware of any changes to AA post 44 so it is a bug in the website. 

**Fixed**.
