### ISSUE TITLE
How are you generating the data files?

### ISSUE THREAD

**Issue by oskapt** [akarnokd/rng-76#37]
I've been looking through your code. There's a lot here, and I imagine that it's quite difficult to keep up with all the changes. I'm interested in your code that diffs patch releases, and I'm curious -- how are you generating the `.js` data files? Writing out the datafiles as JS objects is smart. Have you considered using a database backend for any of this?

**Comment by akarnokd** [comment]
I use [this Java code](https://github.com/akarnokd/akarnokd-misc/blob/master/src/main/java/hu/akarnokd/fallout76/EsmExport.java) to export the datafiles for the patchdiff page. Then then html itself will do the diffing.

> Have you considered using a database backend for any of this?

I don't have a server nor the money to host a database. Files are free on GitHub. It's all or nothing anyways so no benefit of using a query engine either.

**Comment by oskapt** [comment]
Thanks!
