### ISSUE TITLE
S.C.O.R.E. Progression Calculator - Backspace in input field causes soft crash

### ISSUE THREAD

**Issue by fwdekker** [akarnokd/rng-76#9]
In the [S.C.O.R.E. Progression Calculator](https://akarnokd.github.io/rng-76/score.html), removing the input daily or weekly challenge input using backspace causes the page to freeze completely.

To reproduce:
* Open the page with default values
* Select the "Daily Challenge S.C.O.R.E." input
* Press backspace four times

Happens both with Firefox 84.0 and Chrome 87.0.4280.88.

**Comment by akarnokd** [comment]
Thanks. Fixed.

**Comment by fwdekker** [comment]
Wow, that was quick! Thanks!
